#!/usr/bin/env sh

# Sometimes xbps-src builds a bunch of other junk I don't want to be liable for distributing

COMMAND="
  mkdir /work/packages
  
  # cp /work/hostdir/binpkgs/<paskage_name>*.xbps /work/packages

  cd /work/packages
  xbps-rindex -a *
"
echo "Running command: $COMMAND"
sh -c "$COMMAND"

